# Read the documentation: https://fosrestbundle.readthedocs.io/en/3.x/
fos_rest:
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
    routing_loader: false
    view:
        view_response_listener:  true
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: validationErrors
    exception:
        codes:
            'Symfony\Component\HttpKernel\Exception\BadRequestHttpException': 400
            'Symfony\Component\HttpKernel\Exception\NotFoundHttpException': 404
        messages:
            'Symfony\Component\HttpKernel\Exception\BadRequestHttpException': false
            'Symfony\Component\HttpKernel\Exception\NotFoundHttpException': false
        map_exception_codes: true
    format_listener:
        enabled: true
        rules:
            - { path: '^/api', priorities: [ 'json', 'xml' ], fallback_format: 'json', prefer_extension: false }
            - { path: '^/', priorities: ['text/html', '*/*'], fallback_format: 'html', prefer_extension: true }
