# Read the documentation: https://fosrestbundle.readthedocs.io/en/3.x/
fos_rest:
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
    routing_loader: false
    view:
        view_response_listener:  true
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: errors
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
    format_listener:
        enabled: true
        rules:
            - { path: '^/api', priorities: [ 'json', 'xml' ], fallback_format: 'json', prefer_extension: false }
            - { path: '^/', priorities: ['text/html', '*/*'], fallback_format: 'html', prefer_extension: true }
